name: terraform plan

# プルリクエストのOpen、更新、Reopen時にトリガー
on:
  push:
    branches:
      - master

env:
  tf_version: '1.4.2'
  tf_work_dir: '.'
  GITHUB_TOKEN: ${{ secrets.TF_API_TOKEN }}

jobs:
  plan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: terraform fmt
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_subcommand: fmt
          tf_actions_working_dir: ${{ env.tf_work_dir }}

      - name: terraform init
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_subcommand: init
          tf_actions_working_dir: ${{ env.tf_work_dir }}

      - name: terraform validate
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_subcommand: validate
          tf_actions_working_dir: ${{ env.tf_work_dir }}

      - name: terraform plan
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_subcommand: plan
          tf_actions_working_dir: ${{ env.tf_work_dir }}
      
      - name: Start Deployment
        # # terraform planで差分があるときのみ実行
        # if: ${{ steps.plan.outputs.tf_actions_plan_has_changes == 'true' }}
        uses: bobheadxi/deployments@master
        id: deployment
        with:
          step: start
          token: ${{ secrets.TF_API_TOKEN }}
          env: production

      - name: terraform apply
        # # terraform planで差分があるときのみ実行
        # if: ${{ steps.plan.outputs.tf_actions_plan_has_changes == 'true' }}
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_subcommand: apply
          tf_actions_working_dir: ${{ env.tf_work_dir }}

      # Deploymentを終了する
      - name: Finish Deployment
        uses: bobheadxi/deployments@master
        # terraform planで差分があるときのみ実行
        if: ${{ always() && steps.plan.outputs.tf_actions_plan_has_changes == 'true' }}
        with:
          step: finish
          token: ${{ secrets.TF_API_TOKEN}}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}

      
